Report error on grab spot

diff --git a/local/bin/grab-spot b/local/bin/grab-spot
--- a/local/bin/grab-spot
+++ b/local/bin/grab-spot
@@ -11,5 +11,9 @@ fi
 # Only bother downloading if it's more than 3 hours old
 if [ $(find ~/.cache/"$1$2" -mmin +180) ] ; then
 	rate=$(curl "http://rate-exchange-1.appspot.com/currency?from=$1&to=$2" | jshon -e rate)
-	echo "$1$2: $rate" > ~/.cache/"$1$2"
+	if [ $? -ne 0 ] ; then
+		logger "$0: curl error"
+		exit
+	fi
+	printf "$1$2: %.4f" $rate > ~/.cache/"$1$2"
 fi
